### ISSUE TITLE
Learn csv-w schema structure 

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csv-validation#17]
- Learn more on context
- why some schema is not having this 
- why in Ruby implementation 2 types of schema classes are returned as schema (CSV::Schema and Csvw::TableGroup)

more information here https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/

Time box- half day?

**Comment by robons** [comment]
TODO: @robons to signpost to some examples of the CSV-W schemas we're using.
