### ISSUE TITLE
Setup a command-line app

### ISSUE THREAD

**Issue by josepajay** [GSS-Cogs/csv-validation#5]
- Accept source and schema files as command line parameters
- Use a library which makes it easier to use help options ( eg -- help)
- Ensure it executes an actor system 
- Create a validator class which takes in arguments (schema, csv file) and returns response containing errors and warnings

**Comment by ajtucker** [comment]
I've used https://github.com/scopt/scopt over the years. See e.g. https://git.floop.org.uk/alex/csv2rdf/blob/563bce6264e93d3a8456d1e6987a658a2fb522ce/src/main/scala/uk/org/floop/csv2rdf/Run.scala#L139

It's a bit odd in that there are different ways of doing things depending on whether you want to be mutable or immutable, but in the end saves faffing around reinventing commandline parsing.
